import Car from "./assets/images/car.png";
import BCar1 from './assets/images/booking-car-1.png';
import BCar2 from './assets/images/booking-car-2.png';
import BCar3 from './assets/images/booking-car-3.png';
import BCar4 from './assets/images/booking-car-4.png';
import BCar5 from './assets/images/booking-car-5.png';
import BCar6 from './assets/images/booking-car-6.png';
export const cars = [
  {
    id: 1,
    img: BCar1,
    name: "porsche 718 cayman s",
    type: "coupe",
    passengers: 4,
    gear_type: "manual",
    rental_price: 400,
    favorite: false,
  },
  {
    id: 2,
    img: BCar2,
    name: "porsche 718 cayman s",
    type: "coupe",
    passengers: 4,
    gear_type: "manual",
    rental_price: 400,
    favorite: true,
  },
  {
    id: 3,
    img: BCar3,
    name: "porsche 718 cayman s",
    type: "coupe",
    passengers: 4,
    gear_type: "manual",
    rental_price: 400,
    favorite: false,
  },
  {
    id: 4,
    img: BCar4,
    name: "porsche 718 cayman s",
    type: "coupe",
    passengers: 4,
    gear_type: "manual",
    rental_price: 400,
    favorite: false,
  },
  {
    id: 5,
    img: BCar5,
    name: "porsche 718 cayman s",
    type: "coupe",
    passengers: 4,
    gear_type: "manual",
    rental_price: 400,
    favorite: false,
  },
  {
    id: 6,
    img: BCar6,
    name: "porsche 718 cayman s",
    type: "coupe",
    passengers: 4,
    gear_type: "manual",
    rental_price: 400,
    favorite: false,
  },
  {
    id: 7,
    img: BCar1,
    name: "porsche 718 cayman s",
    type: "coupe",
    passengers: 4,
    gear_type: "manual",
    rental_price: 400,
    favorite: false,
  },
  {
    id: 8,
    img: BCar2,
    name: "porsche 718 cayman s",
    type: "coupe",
    passengers: 4,
    gear_type: "manual",
    rental_price: 400,
    favorite: false,
  },
  {
    id: 9,
    img: BCar3,
    name: "porsche 718 cayman s",
    type: "coupe",
    passengers: 4,
    gear_type: "manual",
    rental_price: 400,
    favorite: false,
  },
];
export const carStats = [
  {
    id: 1,
    img: Car,
    name: "porsche 718 cayman s",
    recommended: 64,
    kms: 132,
    rental_price: 400,
    color: "#E1DFA4",
  },
  {
    id: 2,
    img: Car,
    name: "porsche 718 cayman s",
    recommended: 64,
    kms: 132,
    color: "#E3ECF1",
    rental_price: 400,
  },
  {
    id: 3,
    img: Car,
    name: "porsche 718 cayman s",
    recommended: 64,
    kms: 132,
    rental_price: 400,
    color: "#F4E3E5",
  },
];
