import Car from "./assets/images/car.png";
export const cars = [
  {
    id: 1,
    img: "https://www.ccarprice.com/products/Porsche_718_Cayman_2022.jpg",
    name: "porsche 718 cayman s",
    type: "coupe",
    passengers: 4,
    gear_type: "manual",
    rental_price: 400,
    favorite: false,
  },
  {
    id: 2,
    img: "https://imgd.aeplcdn.com/1056x594/cw/ec/23766/Ford-Mustang-Exterior-126883.jpg?wm=1&q=75",
    name: "ford mustang gt",
    type: "coupe",
    passengers: 4,
    gear_type: "manual",
    rental_price: 400,
    favorite: false,
  },
  {
    id: 3,
    img: "https://www.ccarprice.com/products/Toyota-GR-Supra-2020_1.jpg",
    name: "toyata supra gr",
    type: "coupe",
    passengers: 4,
    gear_type: "manual",
    rental_price: 400,
    favorite: true,
  },
  {
    id: 4,
    img: "https://media.ed.edmunds-media.com/bmw/x5/2021/oem/2021_bmw_x5_4dr-suv_m50i_fq_oem_1_815.jpg",
    name: "Bmw x5",
    type: "coupe",
    passengers: 4,
    gear_type: "manual",
    rental_price: 400,
    favorite: true,
  },
  {
    id: 5,
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Chevrolet_Corvette_C8_Stingray_blue.jpg/1024px-Chevrolet_Corvette_C8_Stingray_blue.jpg",
    name: "Chevrolet Corvette",
    type: "coupe",
    passengers: 4,
    gear_type: "manual",
    rental_price: 400,
    favorite: false,
  },
  {
    id: 6,
    img: "https://www.ccarprice.com/products/Toyota_LandCruiser_2022_1.jpg",
    name: "Toyota Land Cruiser",
    type: "coupe",
    passengers: 4,
    gear_type: "manual",
    rental_price: 400,
    favorite: false,
  },
  {
    id: 7,
    img: "https://www.ccarprice.com/products/Toyota_LandCruiser_2022_1.jpg",
    name: "Toyota Land Cruiser",
    type: "coupe",
    passengers: 4,
    gear_type: "manual",
    rental_price: 400,
    favorite: false,
  },
];
export const carStats = [
  {
    id: 1,
    img: Car,
    name: "porsche 718 cayman s",
    recommended: 64,
    kms: 132,
    rental_price: 400,
    color: "#E1DFA4",
  },
  {
    id: 2,
    img: Car,
    name: "porsche 718 cayman s",
    recommended: 64,
    kms: 132,
    color: "#E3ECF1",
    rental_price: 400,
  },
  {
    id: 3,
    img: Car,
    name: "porsche 718 cayman s",
    recommended: 64,
    kms: 132,
    rental_price: 400,
    color: "#F4E3E5",
  },
];
